### ISSUE TITLE
Live editor

### ISSUE THREAD

**Issue by herohamp** [card100/patch#2]
If you like I can host this on a live editor that is running off my server zorgtech.org so that you can live edit and not wait for github pages to update.

**Comment by card100** [comment]
That would be very cool!  Thanks!

**Comment by herohamp** [comment]
@card100 want me to start it up now? PS make sure to push it to git if you update something as I cannot guarantee 100% uptime

**Comment by card100** [comment]
And I would just continue uploading to Git like normal?

**Comment by herohamp** [comment]
yup just download it and use ethier a github client or the github upload button

**Comment by card100** [comment]
Sure, no harm in trying it

**Comment by herohamp** [comment]
ok, I am looking into getting a test docker container setup. and once I can get that finished then I will set it up for you. I just wanna make sure your stuff is separate from my OS ;P

**Comment by herohamp** [comment]
welp my parents are making me shutdown my server till we come back from vacation so I won't have it up for like 2 weeks :(
